/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AssignHotelToManager$Params {
  managerId: number;
  hotelId: number;
}

export function assignHotelToManager(http: HttpClient, rootUrl: string, params: AssignHotelToManager$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, assignHotelToManager.PATH, 'put');
  if (params) {
    rb.query('managerId', params.managerId, {});
    rb.query('hotelId', params.hotelId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

assignHotelToManager.PATH = '/admin/assign-hotel-to-manager';
