/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EducationDto } from '../../models/education-dto';

export interface GetAllEductionByDoctorId$Params {
  doctorId: number;
}

export function getAllEductionByDoctorId(http: HttpClient, rootUrl: string, params: GetAllEductionByDoctorId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EducationDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllEductionByDoctorId.PATH, 'get');
  if (params) {
    rb.path('doctorId', params.doctorId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EducationDto>>;
    })
  );
}

getAllEductionByDoctorId.PATH = '/doctor-profile-setting/education/doctor/view/{doctorId}';
