/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EducationDto } from '../../models/education-dto';

export interface GetAllEduction$Params {
}

export function getAllEduction(http: HttpClient, rootUrl: string, params?: GetAllEduction$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EducationDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllEduction.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EducationDto>>;
    })
  );
}

getAllEduction.PATH = '/doctor-profile-setting/education/view';
