/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorDto } from '../../models/doctor-dto';

export interface GetProfileInfo$Params {
  email: string;
}

export function getProfileInfo(http: HttpClient, rootUrl: string, params: GetProfileInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<DoctorDto>> {
  const rb = new RequestBuilder(rootUrl, getProfileInfo.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DoctorDto>;
    })
  );
}

getProfileInfo.PATH = '/doctor/profile';
