/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorDto } from '../../models/doctor-dto';
import { DoctorSearchDto } from '../../models/doctor-search-dto';

export interface SearchDoctors$Params {
      body: DoctorSearchDto
}

export function searchDoctors(http: HttpClient, rootUrl: string, params: SearchDoctors$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DoctorDto>>> {
  const rb = new RequestBuilder(rootUrl, searchDoctors.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DoctorDto>>;
    })
  );
}

searchDoctors.PATH = '/doctor/search';
