/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentDoctorResponse } from '../../models/appointment-doctor-response';

export interface GetAppointmentsByDoctor$Params {
  id: number;
}

export function getAppointmentsByDoctor(http: HttpClient, rootUrl: string, params: GetAppointmentsByDoctor$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentDoctorResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAppointmentsByDoctor.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppointmentDoctorResponse>>;
    })
  );
}

getAppointmentsByDoctor.PATH = '/appointment/doctor/{id}';
