/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentPatientResponse } from '../../models/appointment-patient-response';

export interface GetAppointmentByPatient$Params {
  appointmentId: number;
}

export function getAppointmentByPatient(http: HttpClient, rootUrl: string, params: GetAppointmentByPatient$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentPatientResponse>> {
  const rb = new RequestBuilder(rootUrl, getAppointmentByPatient.PATH, 'get');
  if (params) {
    rb.path('appointmentId', params.appointmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentPatientResponse>;
    })
  );
}

getAppointmentByPatient.PATH = '/appointment/patient/view/{appointmentId}';
