/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentPatientResponse } from '../../models/appointment-patient-response';

export interface GetAppointmentsByPatient$Params {
  id: number;
}

export function getAppointmentsByPatient(http: HttpClient, rootUrl: string, params: GetAppointmentsByPatient$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentPatientResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAppointmentsByPatient.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppointmentPatientResponse>>;
    })
  );
}

getAppointmentsByPatient.PATH = '/appointment/patient/{id}';
