/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentDoctorResponse } from '../../models/appointment-doctor-response';

export interface GetAppointmentByDoctor$Params {
  appointmentId: number;
}

export function getAppointmentByDoctor(http: HttpClient, rootUrl: string, params: GetAppointmentByDoctor$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentDoctorResponse>> {
  const rb = new RequestBuilder(rootUrl, getAppointmentByDoctor.PATH, 'get');
  if (params) {
    rb.path('appointmentId', params.appointmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentDoctorResponse>;
    })
  );
}

getAppointmentByDoctor.PATH = '/appointment/doctor/view/{appointmentId}';
