/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExperienceDto } from '../../models/experience-dto';

export interface GetAllExperiencesByDoctorId$Params {
  doctorId: number;
}

export function getAllExperiencesByDoctorId(http: HttpClient, rootUrl: string, params: GetAllExperiencesByDoctorId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExperienceDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllExperiencesByDoctorId.PATH, 'get');
  if (params) {
    rb.path('doctorId', params.doctorId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExperienceDto>>;
    })
  );
}

getAllExperiencesByDoctorId.PATH = '/doctor-profile-setting/experience/doctor/view/{doctorId}';
