/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorNoteRequest } from '../../models/doctor-note-request';

export interface GetDoctorNotes$Params {
  healthRecordId: number;
}

export function getDoctorNotes(http: HttpClient, rootUrl: string, params: GetDoctorNotes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DoctorNoteRequest>>> {
  const rb = new RequestBuilder(rootUrl, getDoctorNotes.PATH, 'get');
  if (params) {
    rb.path('healthRecordId', params.healthRecordId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DoctorNoteRequest>>;
    })
  );
}

getDoctorNotes.PATH = '/doctor-notes/view/patient/{healthRecordId}';
