/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorNotesDto } from '../../models/doctor-notes-dto';

export interface UpdateDoctorNote$Params {
  id: number;
  doctorId: number;
      body: DoctorNotesDto
}

export function updateDoctorNote(http: HttpClient, rootUrl: string, params: UpdateDoctorNote$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, updateDoctorNote.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('doctorId', params.doctorId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

updateDoctorNote.PATH = '/doctor-notes/update/{id}';
