/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { detectDisease } from '../fn/plant-disease-controller/detect-disease';
import { DetectDisease$Params } from '../fn/plant-disease-controller/detect-disease';
import { DiseaseResponse } from '../models/disease-response';
import { health } from '../fn/plant-disease-controller/health';
import { Health$Params } from '../fn/plant-disease-controller/health';

@Injectable({ providedIn: 'root' })
export class PlantDiseaseControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `detectDisease()` */
  static readonly DetectDiseasePath = '/detect-disease';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `detectDisease()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  detectDisease$Response(params: DetectDisease$Params, context?: HttpContext): Observable<StrictHttpResponse<DiseaseResponse>> {
    return detectDisease(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `detectDisease$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  detectDisease(params: DetectDisease$Params, context?: HttpContext): Observable<DiseaseResponse> {
    return this.detectDisease$Response(params, context).pipe(
      map((r: StrictHttpResponse<DiseaseResponse>): DiseaseResponse => r.body)
    );
  }

  /** Path part for operation `health()` */
  static readonly HealthPath = '/detect-disease/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `health()` instead.
   *
   * This method doesn't expect any request body.
   */
  health$Response(params?: Health$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return health(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `health$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  health(params?: Health$Params, context?: HttpContext): Observable<{
}> {
    return this.health$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
