/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkplaceDto } from '../../models/workplace-dto';

export interface GetWorkPlaceById$Params {
  id: number;
}

export function getWorkPlaceById(http: HttpClient, rootUrl: string, params: GetWorkPlaceById$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkplaceDto>> {
  const rb = new RequestBuilder(rootUrl, getWorkPlaceById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkplaceDto>;
    })
  );
}

getWorkPlaceById.PATH = '/doctor-profile-setting/workPlace/view/{id}';
