/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkPlaceResponse } from '../../models/work-place-response';

export interface GetWorkPlaceList$Params {
}

export function getWorkPlaceList(http: HttpClient, rootUrl: string, params?: GetWorkPlaceList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkPlaceResponse>>> {
  const rb = new RequestBuilder(rootUrl, getWorkPlaceList.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkPlaceResponse>>;
    })
  );
}

getWorkPlaceList.PATH = '/doctor-profile-setting/workPlace/view';
