/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkplaceDto } from '../../models/workplace-dto';

export interface GetWorkPlaceByDoctorId$Params {
  doctorId: number;
}

export function getWorkPlaceByDoctorId(http: HttpClient, rootUrl: string, params: GetWorkPlaceByDoctorId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkplaceDto>>> {
  const rb = new RequestBuilder(rootUrl, getWorkPlaceByDoctorId.PATH, 'get');
  if (params) {
    rb.path('doctorId', params.doctorId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkplaceDto>>;
    })
  );
}

getWorkPlaceByDoctorId.PATH = '/doctor-profile-setting/workPlace/doctor/view/{doctorId}';
