/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkplaceDto } from '../../models/workplace-dto';

export interface UpdateWorkPlace$Params {
  id: number;
      body?: {
'data': WorkplaceDto;
'gallery'?: Array<Blob>;
'certifications'?: Array<Blob>;
'image'?: Blob;
}
}

export function updateWorkPlace(http: HttpClient, rootUrl: string, params: UpdateWorkPlace$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateWorkPlace.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateWorkPlace.PATH = '/doctor-profile-setting/workPlace/update/{id}';
