/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DiseaseResponse {
  confidence?: number;
  demoMode?: boolean;
  disease?: string;
  location?: string;
  message?: string;
  plant?: string;
  prevention?: Array<string>;
  severity?: string;
  treatment?: Array<string>;
}
