/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthRecordDto } from '../../models/health-record-dto';

export interface GetHealthRecord$Params {
  patientId: number;
}

export function getHealthRecord(http: HttpClient, rootUrl: string, params: GetHealthRecord$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthRecordDto>> {
  const rb = new RequestBuilder(rootUrl, getHealthRecord.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthRecordDto>;
    })
  );
}

getHealthRecord.PATH = '/health-record/view/{patientId}';
