/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthRecordDto } from '../../models/health-record-dto';

export interface UpdateHealthRecord$Params {
  patientId: number;
  updateRequest: HealthRecordDto;
}

export function updateHealthRecord(http: HttpClient, rootUrl: string, params: UpdateHealthRecord$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateHealthRecord.PATH, 'put');
  if (params) {
    rb.path('patientId', params.patientId, {});
    rb.query('updateRequest', params.updateRequest, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateHealthRecord.PATH = '/health-record/update/{patientId}';
