/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RelativeResponse } from '../../models/relative-response';

export interface GetRelatives$Params {
  patientEmail: string;
}

export function getRelatives(http: HttpClient, rootUrl: string, params: GetRelatives$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RelativeResponse>>> {
  const rb = new RequestBuilder(rootUrl, getRelatives.PATH, 'get');
  if (params) {
    rb.path('patientEmail', params.patientEmail, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RelativeResponse>>;
    })
  );
}

getRelatives.PATH = '/relative/view/{patientEmail}';
