/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RelativeResponse } from '../../models/relative-response';

export interface GetRelativeProfile$Params {
  id: number;
}

export function getRelativeProfile(http: HttpClient, rootUrl: string, params: GetRelativeProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<RelativeResponse>> {
  const rb = new RequestBuilder(rootUrl, getRelativeProfile.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RelativeResponse>;
    })
  );
}

getRelativeProfile.PATH = '/relative/relative-profile/{id}';
