/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientResponse1 } from '../../models/patient-response-1';

export interface GetRelativePatient$Params {
  relativeEmail: string;
}

export function getRelativePatient(http: HttpClient, rootUrl: string, params: GetRelativePatient$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PatientResponse1>>> {
  const rb = new RequestBuilder(rootUrl, getRelativePatient.PATH, 'get');
  if (params) {
    rb.path('relativeEmail', params.relativeEmail, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PatientResponse1>>;
    })
  );
}

getRelativePatient.PATH = '/relative/relative-patient/{relativeEmail}';
