/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorStatsDto } from '../../models/doctor-stats-dto';

export interface GetDoctorStats$Params {
  doctorId: number;
}

export function getDoctorStats(http: HttpClient, rootUrl: string, params: GetDoctorStats$Params, context?: HttpContext): Observable<StrictHttpResponse<DoctorStatsDto>> {
  const rb = new RequestBuilder(rootUrl, getDoctorStats.PATH, 'get');
  if (params) {
    rb.path('doctorId', params.doctorId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DoctorStatsDto>;
    })
  );
}

getDoctorStats.PATH = '/reports/doctor/{doctorId}';
