/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientStatsDto } from '../../models/patient-stats-dto';

export interface GetPatientStats$Params {
  patientId: number;
}

export function getPatientStats(http: HttpClient, rootUrl: string, params: GetPatientStats$Params, context?: HttpContext): Observable<StrictHttpResponse<PatientStatsDto>> {
  const rb = new RequestBuilder(rootUrl, getPatientStats.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PatientStatsDto>;
    })
  );
}

getPatientStats.PATH = '/reports/patient/{patientId}';
