/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthenticateResponse } from '../../models/authenticate-response';
import { VerificationRequest } from '../../models/verification-request';

export interface VerifyCode$Params {
      body: VerificationRequest
}

export function verifyCode(http: HttpClient, rootUrl: string, params: VerifyCode$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticateResponse>> {
  const rb = new RequestBuilder(rootUrl, verifyCode.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthenticateResponse>;
    })
  );
}

verifyCode.PATH = '/auth/verify-login';
