/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AwardDto } from '../../models/award-dto';

export interface GetAwardById$Params {
  id: number;
}

export function getAwardById(http: HttpClient, rootUrl: string, params: GetAwardById$Params, context?: HttpContext): Observable<StrictHttpResponse<AwardDto>> {
  const rb = new RequestBuilder(rootUrl, getAwardById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AwardDto>;
    })
  );
}

getAwardById.PATH = '/doctor-profile-setting/award/view/{id}';
