/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MedicalHistoryDto } from '../../models/medical-history-dto';

export interface GetMedicalHistory$Params {
  healthRecordId: number;
}

export function getMedicalHistory(http: HttpClient, rootUrl: string, params: GetMedicalHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MedicalHistoryDto>>> {
  const rb = new RequestBuilder(rootUrl, getMedicalHistory.PATH, 'get');
  if (params) {
    rb.path('healthRecordId', params.healthRecordId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MedicalHistoryDto>>;
    })
  );
}

getMedicalHistory.PATH = '/medical-history/view/{healthRecordId}';
