/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdherenceSummaryDto } from '../../models/adherence-summary-dto';

export interface GetAdherenceHistory$Params {
  patientId: number;
}

export function getAdherenceHistory(http: HttpClient, rootUrl: string, params: GetAdherenceHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<AdherenceSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, getAdherenceHistory.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdherenceSummaryDto>;
    })
  );
}

getAdherenceHistory.PATH = '/medication-reminder/adherence/{patientId}';
