/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReminderDto } from '../../models/reminder-dto';

export interface GetTodaysReminders$Params {
  patientId: number;
}

export function getTodaysReminders(http: HttpClient, rootUrl: string, params: GetTodaysReminders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReminderDto>>> {
  const rb = new RequestBuilder(rootUrl, getTodaysReminders.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReminderDto>>;
    })
  );
}

getTodaysReminders.PATH = '/medication-reminder/today/{patientId}';
