/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientAdherenceOverviewDto } from '../../models/patient-adherence-overview-dto';

export interface GetDoctorOverview$Params {
  doctorId: number;
}

export function getDoctorOverview(http: HttpClient, rootUrl: string, params: GetDoctorOverview$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PatientAdherenceOverviewDto>>> {
  const rb = new RequestBuilder(rootUrl, getDoctorOverview.PATH, 'get');
  if (params) {
    rb.path('doctorId', params.doctorId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PatientAdherenceOverviewDto>>;
    })
  );
}

getDoctorOverview.PATH = '/medication-reminder/doctor-overview/{doctorId}';
