/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateReminderStatus$Params {
  id: number;
  status: 'PENDING' | 'TAKEN' | 'SKIPPED' | 'MISSED';
}

export function updateReminderStatus(http: HttpClient, rootUrl: string, params: UpdateReminderStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateReminderStatus.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateReminderStatus.PATH = '/medication-reminder/reminders/{id}/{status}';
