/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BusinessHoursDto } from '../../models/business-hours-dto';

export interface GetBusinessHours$Params {
  doctorId: number;
}

export function getBusinessHours(http: HttpClient, rootUrl: string, params: GetBusinessHours$Params, context?: HttpContext): Observable<StrictHttpResponse<BusinessHoursDto>> {
  const rb = new RequestBuilder(rootUrl, getBusinessHours.PATH, 'get');
  if (params) {
    rb.path('doctorId', params.doctorId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BusinessHoursDto>;
    })
  );
}

getBusinessHours.PATH = '/doctor-profile-setting/businessHours/view/{doctorId}';
