/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobDto } from '../../models/job-dto';

export interface UpdateJob$Params {
  Authorization: string;
  id: number;
      body?: {
'data': JobDto;
'image'?: Blob;
}
}

export function updateJob(http: HttpClient, rootUrl: string, params: UpdateJob$Params, context?: HttpContext): Observable<StrictHttpResponse<JobDto>> {
  const rb = new RequestBuilder(rootUrl, updateJob.PATH, 'put');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobDto>;
    })
  );
}

updateJob.PATH = '/job/{id}';
