/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceDto } from '../../models/service-dto';

export interface GetService$Params {
  id: number;
}

export function getService(http: HttpClient, rootUrl: string, params: GetService$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceDto>> {
  const rb = new RequestBuilder(rootUrl, getService.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceDto>;
    })
  );
}

getService.PATH = '/doctor-profile-setting/service/view/{id}';
