/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DiseaseResponse } from '../../models/disease-response';

export interface DetectDisease$Params {
  data: string;
      body?: {
'image': Blob;
}
}

export function detectDisease(http: HttpClient, rootUrl: string, params: DetectDisease$Params, context?: HttpContext): Observable<StrictHttpResponse<DiseaseResponse>> {
  const rb = new RequestBuilder(rootUrl, detectDisease.PATH, 'post');
  if (params) {
    rb.query('data', params.data, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiseaseResponse>;
    })
  );
}

detectDisease.PATH = '/detect-disease';
