/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticateResponse } from './models/authenticate-response';
export type { AuthenticationRequest } from './models/authentication-request';
export type { DiseaseResponse } from './models/disease-response';
export type { Location } from './models/location';
export type { RegistrationRequest } from './models/registration-request';
export type { UserDto } from './models/user-dto';
export type { VerificationRequest } from './models/verification-request';
